name = "SKSMPGP"
author = "FutureLizard205"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41a2cf33b5b556d165c81628270ff97bd88348e97068f22c3aefb73602b0c853"

[versions]
forge = "40.1.52"
minecraft = "1.18.2"
