name = "SKSMPGP"
author = "FutureLizard205"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "582168df8eccddc41046d0e8af775d18dd90a5d018d55b7bfee201cceb7a362b"

[versions]
forge = "40.1.52"
minecraft = "1.18.2"
