name = "SKSMPGP"
author = "FutureLizard205"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a538c6c1a2a6bd95128fa95951a53ac289a164c155ed84f407848b55b2204d79"

[versions]
forge = "40.1.52"
minecraft = "1.18.2"
