name = "SKSMPGP"
author = "FutureLizard205"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4b5878edf58272011e7cdde9c838196e69b674e0727ac01b85a27e5811d0927"

[versions]
forge = "40.1.52"
minecraft = "1.18.2"
